

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	int32_t capacity;
	int32_t len;
	uint8_t *data;
} RustBuffer;

typedef int32_t (*ForeignCallback)(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);

// Task defined in Rust that Go executes
typedef void (*RustTaskCallback)(const void *, int8_t);

// Callback to execute Rust tasks using a Go routine
//
// Args:
//   executor: ForeignExecutor lowered into a uint64_t value
//   delay: Delay in MS
//   task: RustTaskCallback to call
//   task_data: data to pass the task callback
typedef int8_t (*ForeignExecutorCallback)(uint64_t, uint32_t, RustTaskCallback, void *);

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

// Continuation callback for UniFFI Futures
typedef void (*RustFutureContinuation)(void * , int8_t);

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H

// Needed because we can't execute the callback directly from go.
void cgo_rust_task_callback_bridge_breez_sdk(RustTaskCallback, const void *, int8_t);

int8_t uniffiForeignExecutorCallbackbreez_sdk(uint64_t, uint32_t, RustTaskCallback, void*);

void uniffiFutureContinuationCallbackbreez_sdk(void*, int8_t);

void uniffi_breez_sdk_bindings_fn_free_blockingbreezservices(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_backup(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_backup_status(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_buy_bitcoin(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_check_message(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_claim_reverse_swap(
	void* ptr,
	RustBuffer lockup_address,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_close_lsp_channels(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_configure_node(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_connect_lsp(
	void* ptr,
	RustBuffer lsp_id,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_disconnect(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_execute_dev_command(
	void* ptr,
	RustBuffer command,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_fetch_fiat_rates(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_fetch_lsp_info(
	void* ptr,
	RustBuffer lsp_id,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_fetch_reverse_swap_fees(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_generate_diagnostic_data(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_in_progress_onchain_payments(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_in_progress_swap(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_list_fiat_currencies(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_list_lsps(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_list_payments(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_list_refundables(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_list_swaps(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_lnurl_auth(
	void* ptr,
	RustBuffer req_data,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_lsp_id(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_lsp_info(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_node_credentials(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_node_info(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_onchain_payment_limits(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_open_channel_fee(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_pay_lnurl(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_pay_onchain(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_payment_by_hash(
	void* ptr,
	RustBuffer hash,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_prepare_onchain_payment(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_prepare_redeem_onchain_funds(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_prepare_refund(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_receive_onchain(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_receive_payment(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_recommended_fees(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_redeem_onchain_funds(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_redeem_swap(
	void* ptr,
	RustBuffer swap_address,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_refund(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_register_webhook(
	void* ptr,
	RustBuffer webhook_url,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_report_issue(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_rescan_swaps(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_send_payment(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_send_spontaneous_payment(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_set_payment_metadata(
	void* ptr,
	RustBuffer hash,
	RustBuffer metadata,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_sign_message(
	void* ptr,
	RustBuffer req,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_sync(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_unregister_webhook(
	void* ptr,
	RustBuffer webhook_url,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_method_blockingbreezservices_withdraw_lnurl(
	void* ptr,
	RustBuffer request,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_bindings_fn_init_callback_eventlistener(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_bindings_fn_init_callback_logstream(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void* uniffi_breez_sdk_bindings_fn_func_connect(
	RustBuffer req,
	uint64_t listener,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_func_default_config(
	RustBuffer env_type,
	RustBuffer api_key,
	RustBuffer node_config,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_func_mnemonic_to_seed(
	RustBuffer phrase,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_func_parse_input(
	RustBuffer s,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_func_parse_invoice(
	RustBuffer invoice,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_func_service_health_check(
	RustBuffer api_key,
	RustCallStatus* out_status
);

void uniffi_breez_sdk_bindings_fn_func_set_log_stream(
	uint64_t log_stream,
	RustCallStatus* out_status
);

RustBuffer uniffi_breez_sdk_bindings_fn_func_static_backup(
	RustBuffer req,
	RustCallStatus* out_status
);

RustBuffer ffi_breez_sdk_bindings_rustbuffer_alloc(
	int32_t size,
	RustCallStatus* out_status
);

RustBuffer ffi_breez_sdk_bindings_rustbuffer_from_bytes(
	ForeignBytes bytes,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rustbuffer_free(
	RustBuffer buf,
	RustCallStatus* out_status
);

RustBuffer ffi_breez_sdk_bindings_rustbuffer_reserve(
	RustBuffer buf,
	int32_t additional,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_continuation_callback_set(
	RustFutureContinuation callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_poll_u8(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_cancel_u8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_free_u8(
	void* handle,
	RustCallStatus* out_status
);

uint8_t ffi_breez_sdk_bindings_rust_future_complete_u8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_poll_i8(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_cancel_i8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_free_i8(
	void* handle,
	RustCallStatus* out_status
);

int8_t ffi_breez_sdk_bindings_rust_future_complete_i8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_poll_u16(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_cancel_u16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_free_u16(
	void* handle,
	RustCallStatus* out_status
);

uint16_t ffi_breez_sdk_bindings_rust_future_complete_u16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_poll_i16(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_cancel_i16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_free_i16(
	void* handle,
	RustCallStatus* out_status
);

int16_t ffi_breez_sdk_bindings_rust_future_complete_i16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_poll_u32(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_cancel_u32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_free_u32(
	void* handle,
	RustCallStatus* out_status
);

uint32_t ffi_breez_sdk_bindings_rust_future_complete_u32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_poll_i32(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_cancel_i32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_free_i32(
	void* handle,
	RustCallStatus* out_status
);

int32_t ffi_breez_sdk_bindings_rust_future_complete_i32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_poll_u64(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_cancel_u64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_free_u64(
	void* handle,
	RustCallStatus* out_status
);

uint64_t ffi_breez_sdk_bindings_rust_future_complete_u64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_poll_i64(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_cancel_i64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_free_i64(
	void* handle,
	RustCallStatus* out_status
);

int64_t ffi_breez_sdk_bindings_rust_future_complete_i64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_poll_f32(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_cancel_f32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_free_f32(
	void* handle,
	RustCallStatus* out_status
);

float ffi_breez_sdk_bindings_rust_future_complete_f32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_poll_f64(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_cancel_f64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_free_f64(
	void* handle,
	RustCallStatus* out_status
);

double ffi_breez_sdk_bindings_rust_future_complete_f64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_poll_pointer(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_cancel_pointer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_free_pointer(
	void* handle,
	RustCallStatus* out_status
);

void* ffi_breez_sdk_bindings_rust_future_complete_pointer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_poll_rust_buffer(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_cancel_rust_buffer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_free_rust_buffer(
	void* handle,
	RustCallStatus* out_status
);

RustBuffer ffi_breez_sdk_bindings_rust_future_complete_rust_buffer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_poll_void(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_cancel_void(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_free_void(
	void* handle,
	RustCallStatus* out_status
);

void ffi_breez_sdk_bindings_rust_future_complete_void(
	void* handle,
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_func_connect(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_func_default_config(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_func_mnemonic_to_seed(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_func_parse_input(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_func_parse_invoice(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_func_service_health_check(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_func_set_log_stream(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_func_static_backup(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_backup(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_backup_status(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_buy_bitcoin(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_check_message(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_claim_reverse_swap(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_close_lsp_channels(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_configure_node(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_connect_lsp(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_disconnect(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_execute_dev_command(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_fetch_fiat_rates(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_fetch_lsp_info(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_fetch_reverse_swap_fees(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_generate_diagnostic_data(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_in_progress_onchain_payments(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_in_progress_swap(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_list_fiat_currencies(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_list_lsps(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_list_payments(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_list_refundables(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_list_swaps(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_lnurl_auth(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_lsp_id(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_lsp_info(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_node_credentials(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_node_info(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_onchain_payment_limits(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_open_channel_fee(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_pay_lnurl(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_pay_onchain(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_payment_by_hash(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_prepare_onchain_payment(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_prepare_redeem_onchain_funds(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_prepare_refund(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_receive_onchain(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_receive_payment(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_recommended_fees(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_redeem_onchain_funds(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_redeem_swap(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_refund(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_register_webhook(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_report_issue(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_rescan_swaps(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_send_payment(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_send_spontaneous_payment(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_set_payment_metadata(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_sign_message(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_sync(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_unregister_webhook(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_blockingbreezservices_withdraw_lnurl(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_eventlistener_on_event(
	RustCallStatus* out_status
);

uint16_t uniffi_breez_sdk_bindings_checksum_method_logstream_log(
	RustCallStatus* out_status
);

uint32_t ffi_breez_sdk_bindings_uniffi_contract_version(
	RustCallStatus* out_status
);


int32_t breez_sdk_bindings_cgo_EventListener(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);
int32_t breez_sdk_bindings_cgo_LogStream(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);

